### ISSUE TITLE
Compatibility with node9

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/node-cartodb-psql#30]
Current master release is incompatible with node9 (not sure about 8) due to the `pg` dependency:
```bash
$ make
npm install

> pg@2.6.2-cdb4 install /home/raul/dev/public/node-cartodb-psql/node_modules/pg
> node-gyp rebuild || (exit 0)

make[1]: Entering directory '/home/raul/dev/public/node-cartodb-psql/node_modules/pg/build'
  CXX(target) Release/obj.target/binding/src/binding.o
../src/binding.cc:40:38: error: expected class-name before '{' token
 class Connection : public ObjectWrap {
```

The cpp file was removed in the main repository in the release 4.

I've solved temporarily by switching the dependency branch from `6.1.6-cdb1` to `cdb-6.1` but there are too many changes between them, and even more with the current main release (7.2).

@rochoa Can you please have a look and, if appropriate, redirect the issue to the proper squad for deeper investigation?

**Comment by Algunenano** [comment]
I discovered this because the animated aggregation was failing randomly and I kept getting messages like this in the tiler logs:
```
[2017-12-12 09:46:57.599] [ERROR] [default] - Uncaught exception: TypeError: Cannot read property 'create' of undefined
    at Array.floatArrayParser (/opt/carto/tiler/node_modules/cartodb-psql/lib/psql.js:21:34)
    at new eval (eval at Result.addFields (/opt/carto/tiler/node_modules/pg/lib/result.js:100:18), <anonymous>:6:61)
    at Result.parseRow (/opt/carto/tiler/node_modules/pg/lib/result.js:61:10)
    at Query.handleDataRow (/opt/carto/tiler/node_modules/pg/lib/query.js:62:26)
    at Connection.<anonymous> (/opt/carto/tiler/node_modules/pg/lib/client.js:96:24)
    at Connection.emit (events.js:159:13)
    at Connection.<anonymous> (/opt/carto/tiler/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
```

After changing the branch that error seems to be gone (fingers crossed).

**Comment by dgaubert** [comment]
we DONT support neither node 8 nor node 9. What are you trying to do?

**Comment by Algunenano** [comment]
Running the platform in my local machine

**Comment by dgaubert** [comment]
Use Node 6 instead, is what we have in production currently:

```
$ node -v
v6.9.2
$ yarn --version
0.27.5
$ npm -v
3.10.9
```

HTH

**Comment by Algunenano** [comment]
Has this been solved? Windshaft is still pointing to `^0.10.1` which uses pg `cartodb/node-postgres#6.1.6-cdb1` that isn't compatible with node9

**Comment by rafatower** [comment]
Sorry, I closed this because I took it for fixed with a merged PR.

Not a priority but nothing against making it eventually compatible, if that does not harm our production platform.

**Comment by Algunenano** [comment]
As I was getting tired of hacking around this issue I decided to downgrade and use the latest node 6.X release, but it also fails at compilation:

```
[raul node-cartodb-psql]$ node -v
v6.14.2
[raul node-cartodb-psql]$ npm install

> pg@2.6.2-cdb4 install /home/raul/dev/public/node-cartodb-psql/node_modules/pg
> node-gyp rebuild || (exit 0)

make: Entering directory '/home/raul/dev/public/node-cartodb-psql/node_modules/pg/build'
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from /home/raul/.node-gyp/6.14.2/include/node/node.h:42,
                 from ../src/binding.cc:3:
/home/raul/.node-gyp/6.14.2/include/node/v8.h: In static member function ‘static void v8::V8::RemoveGCPrologueCallback(v8::GCCallback)’
/home/raul/.node-gyp/6.14.2/include/node/v8.h:8720:57: warning: cast between incompatible function types from ‘v8::GCCallback’ {aka ‘void (*)(v8::GCType, v8::GCCallbackFlags)’} to ‘v8::Isolate::GCCallback’ {aka ‘void (*)(v8::Isolate*, v8::GCType, v8::GCCallbackFlags)’} [-Wcast-function-type]
       reinterpret_cast<v8::Isolate::GCCallback>(callback));
                                                         ^
/home/raul/.node-gyp/6.14.2/include/node/v8.h: In static member function ‘static void v8::V8::RemoveGCEpilogueCallback(v8::GCCallback)’
/home/raul/.node-gyp/6.14.2/include/node/v8.h:8727:57: warning: cast between incompatible function types from ‘v8::GCCallback’ {aka ‘void (*)(v8::GCType, v8::GCCallbackFlags)’} to ‘v8::Isolate::GCCallback’ {aka ‘void (*)(v8::Isolate*, v8::GCType, v8::GCCallbackFlags)’} [-Wcast-function-type]
       reinterpret_cast<v8::Isolate::GCCallback>(callback));
                                                         ^
../src/binding.cc: At global scope
../src/binding.cc:40:38: error: expected class-name before ‘{’ token
 class Connection : public ObjectWrap {



[...]


../src/binding.cc:940:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(binding, init)
 ^~~~~~~~~~~
In file included from /home/raul/.node-gyp/6.14.2/include/node/node.h:42,
                 from ../src/binding.cc:3:
/home/raul/.node-gyp/6.14.2/include/node/v8.h: In instantiation of ‘static void v8::NonCopyablePersistentTraits<T>::Uncompilable() [with O = v8::Object; T = v8::String]’
/home/raul/.node-gyp/6.14.2/include/node/v8.h:689:25:   required from ‘static void v8::NonCopyablePersistentTraits<T>::Copy(const v8::Persistent<S, M>&, v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent*) [with S = v8::String; M = v8::NonCopyablePersistentTraits<v8::String>; T = v8::String; v8::NonCopyablePersistentTraits<T>::NonCopyablePersistent = v8::Persistent<v8::String>]’
/home/raul/.node-gyp/6.14.2/include/node/v8.h:7578:10:   required from ‘void v8::Persistent<T, M>::Copy(const v8::Persistent<S, M>&) [with S = v8::String; M2 = v8::NonCopyablePersistentTraits<v8::String>; T = v8::String; M = v8::NonCopyablePersistentTraits<v8::String>]’
/home/raul/.node-gyp/6.14.2/include/node/v8.h:755:5:   required from ‘v8::Persistent<T, M>::Persistent(const v8::Persistent<T, M>&) [with T = v8::String; M = v8::NonCopyablePersistentTraits<v8::String>]’
../src/binding.cc:728:68:   required from here
/home/raul/.node-gyp/6.14.2/include/node/v8.h:188:37: error: cannot convert ‘v8::Primitive*’ to ‘v8::Object* volatile’ in assignment
     *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/home/raul/.node-gyp/6.14.2/include/node/v8.h:693:5: note: in expansion of macro ‘TYPE_CHECK’
     TYPE_CHECK(O, Primitive);
     ^~~~~~~~~~
make: *** [binding.target.mk:94: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/raul/dev/public/node-cartodb-psql/node_modules/pg/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.16.6-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/raul/dev/public/node-cartodb-psql/node_modules/pg
gyp ERR! node -v v6.14.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm notice created a lockfile as package-lock.json. You should commit this file.
added 110 packages from 458 contributors in 5.946s
```

I've tested in another machine with node 8.5.0 and it also fails, but I've noticed that `yarn` doesn't print any error a it seems it doesn't compile anything (yarn v0.27.5). I wonder if that C file is really necessary (it was removed from the upstream project several releases ago).
